[package]
name = "sleep_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
